export const API_DATA_REQUEST = 'API_DATA_REQUEST';
export const API_DATA_SUCCESS = 'API_DATA_SUCCESS';
export const API_DATA_FAIL = 'API_DATA_FAIL';

export const POKEMON_DATA_REQUEST = 'POKEMON_DATA_REQUEST';
export const POKEMON_DATA_SUCCESS = 'POKEMON_DATA_SUCCESS';
export const POKEMON_DATA_FAIL = 'POKEMON_DATA_FAIL';
export const POKEMON_DATA_RESET = 'POKEMON_DATA_RESET';
